-- CREATION of DB
CREATE DATABASE Bank;

-- CHOOSE DB
USE Bank;

-- CONSTRAINTS
-- PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, DEFAULT

-- CREATION of Table
CREATE TABLE ACCOUNT (
	ID INT PRIMARY KEY,
    AC_NAME VARCHAR(25) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
);

-- DROP
DROP TABLE ACCOUNT;

SELECT * FROM ACCOUNT;

INSERT INTO ACCOUNT 
	(ID, AC_NAME, BALANCE) VALUES
		(1, "Ram", 100000),
		(2, "Lakshman", 40000),
		(3, "Bharat", 90000),
		(4, "Shatrughan", 80000);

-- ADD - ADDS COLUMN
ALTER TABLE ACCOUNT ADD age INT NOT NULL;

-- MODIFY - TYPE
ALTER TABLE ACCOUNT MODIFY AC_NAME CHAR(25) UNIQUE;

-- DESC
DESC ACCOUNT;

-- CHANGE COLUMN
ALTER TABLE ACCOUNT CHANGE COLUMN AC_NAME NAME CHAR(25) NOT NULL;

-- DROP
ALTER TABLE ACCOUNT DROP COLUMN AGE;

-- RENAME TABLE ITSELF
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;
-- ALTER TABLE ACCOUNT_DETAILS RENAME TO ACCOUNT; 


